services:
  web:
    build:
      context: .
    volumes:
      - .:/app
      - node_modules_cache:/app/node_modules
      - pnpm_cache:/usr/local/pnpm
    ports:
      - "4490:4490"
      - "4491:4491"
volumes:
  node_modules_cache:
  pnpm_cache:
